#!/usr/bin/env bash
set -euo pipefail

if command -v container &>/dev/null; then
	CMD="container"
elif command -v podman &>/dev/null; then
	CMD="podman"
elif command -v docker &>/dev/null; then
	CMD="docker"
else
	cat <<EOF >&2
Error: No container runtime found. Supported container runtimes:
  - Apple Container
  - Podman
  - Docker
EOF
	exit 1
fi

"${CMD}" "$@"
