#!/usr/bin/env bash
set -euo pipefail

[[ -f test/bats/bin/bats ]] || git submodule update --init --recursive

run_tests_locally() {
	test/bats/bin/bats "${@:-test}"
}

run_tests_in_container() {
	local distro="$1"; shift
	test/container-cmd run --rm -it \
		-v "${PWD}":/usr/src/project \
		-w /usr/src/project \
		-e TEST_IS_DISTRO_CONTAINER=1 \
		"${distro}" \
		test/bats/bin/bats "$@"
}

main() {
	local options OPTARG
	local -i OPTIND
	local -i no_shellcheck=0
	local distro="local"
	export TEST_SERVER_BASE_IMAGE="debian:13"
	while getopts "cd:s:" options; do
		case "${options}" in
			c) no_shellcheck=1 ;;
			d) distro="${OPTARG}" ;;
			s) TEST_SERVER_BASE_IMAGE="${OPTARG}" ;;
			*) echo "$0: Invalid option: -${OPTARG}" ;;
		esac
	done
	shift $(( OPTIND - 1 ))

	case "${distro}" in
		local) run_tests_locally "${@:-test}" ;;
		*) run_tests_in_container "${distro}" "${@:-test}" ;;
	esac

	(( no_shellcheck )) || test/shellcheck
}

main "$@"
