#!/usr/bin/env bash
set -e

prune() {
	podman container prune
	podman image prune
	podman system prune -a

	sudo podman container prune
	sudo podman image prune
	sudo podman system prune -a
}

# prune

sudo apt update
sudo apt upgrade -y

sudo apt install -y \
	podman \
	podman-compose

sudo apt autoremove -y
