#!/usr/bin/env bash
# shellcheck disable=SC1091,SC1094,SC2154
set -euo pipefail

PROGRAM="hose"
source "lib/all.bash"
source "src/shared/config.bash"

hose::usage() {
	cat <<EOF

╒════╕
│ ┌┐ │ hose $(cat version.txt)
└─┘└─┘

usage: ${PROGRAM} [options] <command> [<args>]

options:
  -c <config>   Path to configuration file (default: ./hose.conf)
  -h            Show this help message

commands:
  c|config [<section>]     Print configuration (or specific section if specified)
  p|plugins                List plugins with their status (✓ used, - unused, x invalid)
  g|genconf [<plugins>]    Print all available plugin config default keys and values
  a|about [<plugins>]      Show plugin description
  i|info [<plugins>]       Show service information and links
  u|up [<plugins>]         Start or enable services
  d|down [<plugins>]       Stop or disable services
  s|status [<plugins>]     Show service health and status information
  m|metrics [<interval>]   Display real-time system metrics (default: 10s refresh)
  l|logs                   Browse server logs
  r|reboot                 Reboot server
EOF
}

hose::sync_files() {
	local tmp_env
	tmp_env="$(mktemp -d)/.env"
	cat <<EOF > "${tmp_env}"
CLICOLOR='${CLICOLOR}'
LOG_QUIET='${LOG_QUIET}'
HOSE_PLUGINS_HOME='${config_hose_remote_path}/${HOSE_PLUGINS_HOME##*/}'
HOSE_CONFIG='${config_hose_remote_path}/${HOSE_CONFIG##*/}'
EOF

	rsync ${q:+"-q"} -acP --delete -e ssh \
		"${tmp_env}" \
		"${HOSE_CONFIG}" \
		"lib" \
		"src" \
		"${HOSE_PLUGINS_HOME}" \
		"${config_hose_user}@${config_hose_host}:${config_hose_remote_path}"
}

hose::run_on_server() {
	hose::config::load_hose
	(( LOG_QUIET )) && local -i q=1

	log_info "Copying ${config_hose_ssh_pub_key} to ${config_hose_user}@${config_hose_host}..."
		log_divider
			ssh-copy-id -i "${config_hose_ssh_pub_key}" "${config_hose_user}@${config_hose_host}"
		log_divider
	log_info_done "Copying SSH key done."

	log_info "Installing essential packages on ${config_hose_user}@${config_hose_host}..."
		log_divider
			ssh ${q:+"-q"} -t "${config_hose_user}@${config_hose_host}" "$(cat "src/essential_packages.txt"); hose::server::install_essential_packages"
		log_divider
	log_info_done "Installing essential packages done."

	log_info "Syncing files to ${config_hose_user}@${config_hose_host}:${config_hose_remote_path}..."
		log_divider
			hose::sync_files
		log_divider
	log_info_done "Syncing files done."

	ssh ${q:+"-q"} -t "${config_hose_user}@${config_hose_host}" "${config_hose_remote_path}/src/hose-server" "$@"
}

# for testing and debugging
__hose_env() {
	if [[ "$1" == "--config" ]]; then
		local section="$2"
		case "${section}" in
			hose) hose::config::load_hose ;;
			*) hose::config::load "$2" ;;
		esac
		shift 2
	fi

	declare -p "$1"
}

hose::main() {
	HOSE_PLUGINS_HOME="${HOSE_PLUGINS_HOME:-"${PWD}/plugins"}"
	HOSE_CONFIG="${HOSE_CONFIG:-"${PWD}/hose.conf"}"
	CLICOLOR="${CLICOLOR:-1}"
	LOG_QUIET=0

	[[ -d "${HOSE_PLUGINS_HOME}" ]] || fatal "${PROGRAM}: Plugins directory does not exist: ${HOSE_PLUGINS_HOME}"

	local options OPTARG
	local -i OPTIND
	while getopts ":hc:q" options; do
		case "${options}" in
			h) hose::usage; return ;;
			c) HOSE_CONFIG="${OPTARG}" ;;
			q) LOG_QUIET=1 ;;
			*) fatal "${PROGRAM}: Invalid option: -${OPTARG}" ;;
		esac
	done
	shift $(( OPTIND - 1 ))

	if (( ! $# )); then
		hose::usage
		exit 1
	fi

	[[ "${HOSE_CONFIG}" == /* ]] || HOSE_CONFIG="${PWD}/${HOSE_CONFIG}"

	local cmd="$1"; shift
	case "${cmd}" in
		c) cmd="config" ;;
		p) cmd="plugins" ;;
		g) cmd="genconf" ;;
		a) cmd="about" ;;
		i) cmd="info" ;;
		u) cmd="up" ;;
		d) cmd="down" ;;
		s) cmd="status" ;;
		m) cmd="metrics" ;;
		l) cmd="logs" ;;
		r) cmd="reboot" ;;
	esac
	case "${cmd}" in
		env) __hose_env "$@" ;; # for testing and debugging
		config | plugins | genconf) source "src/hose-config.bash" "${cmd}" "$@" ;;
		sync | server-env | metrics | logs | about | info | up | down | status) hose::run_on_server "${cmd}" "$@" ;;
		reboot)
			hose::config::load_hose
			ssh -t "${config_hose_user}@${config_hose_host}" "sudo reboot"
			;;
		*) fatal "${PROGRAM}: Unknown command: ${cmd}" ;;
	esac
}

hose::main "$@"
