#!/usr/bin/env bash
# shellcheck disable=SC1091,SC1094
set -euo pipefail

PROGRAM="hose"
source "lib/all.bash"
source "src/shared/config.bash"

hose::usage() {
	cat <<EOF

╒════╕
│ ┌┐ │ hose $(cat version.txt)
└─┘└─┘

usage: ${PROGRAM} [options] <command> [<args>]

options:
  -c <config>   Path to configuration file (default: ./hose.conf)
  -h            Show this help message

commands:
 config [<section>]   Print config
 plugins              Print plugins
EOF
}

# shellcheck disable=SC2154
hose::sync_files() {
	local tmp_env
	tmp_env="$(mktemp -d)/.env"
	cat <<EOF > "${tmp_env}"
CLICOLOR='${CLICOLOR}'
LOG_QUIET='${LOG_QUIET}'
HOSE_PLUGINS_HOME='${config_hose_remote_path}/${HOSE_PLUGINS_HOME##*/}'
HOSE_CONFIG='${config_hose_remote_path}/${HOSE_CONFIG##*/}'
EOF

	rsync -acP --delete -e ssh \
		"${tmp_env}" \
		"${HOSE_CONFIG}" \
		"lib" \
		"src" \
		"${HOSE_PLUGINS_HOME}" \
		"${config_hose_user}@${config_hose_host}:${config_hose_remote_path}"
}

hose::run_on_server() {
	hose::config::load_hose

	log_info "Syncing files to ${config_hose_user}@${config_hose_host}:${config_hose_remote_path}..."
		log_divider
			hose::sync_files
		log_divider
	log_info_done "Syncing files done."

	ssh -t "${config_hose_user}@${config_hose_host}" "${config_hose_remote_path}/src/hose-server" "$@"
}

# for testing and debugging
__hose_env() {
	if [[ "$1" == "--config" ]]; then
		local section="$2"
		case "${section}" in
			hose) hose::config::load_hose ;;
			*) hose::config::declare_vars "$2" ;;
		esac
		shift 2
	fi

	declare -p "$1"
}

hose::main() {
	HOSE_PLUGINS_HOME="${HOSE_PLUGINS_HOME:-"${PWD}/plugins"}"
	HOSE_CONFIG="${HOSE_CONFIG:-"${PWD}/hose.conf"}"
	LOG_QUIET=0

	[[ -d "${HOSE_PLUGINS_HOME}" ]] || fatal "${PROGRAM}: Plugins directory does not exist: ${HOSE_PLUGINS_HOME}"

	local options OPTARG
	local -i OPTIND
	while getopts ":hc:q" options; do
		case "${options}" in
			h) hose::usage; return ;;
			c) HOSE_CONFIG="${OPTARG}" ;;
			q) LOG_QUIET=1 ;;
			*) fatal "${PROGRAM}: Invalid option: -${OPTARG}" ;;
		esac
	done
	shift $(( OPTIND - 1 ))

	if (( ! $# )); then
		hose::usage
		exit 1
	fi

	[[ "${HOSE_CONFIG}" == /* ]] || HOSE_CONFIG="${PWD}/${HOSE_CONFIG}"

	local cmd="$1"; shift
	case "${cmd}" in
		env) __hose_env "$@" ;; # for testing and debugging
		config) source "src/hose-config.bash" "${cmd}" "$@" ;;
		plugins) source "src/hose-config.bash" "${cmd}" "$@" ;;
		sync | server-env | about | info | up | down | status) hose::run_on_server "${cmd}" "$@" ;;
		*) fatal "${PROGRAM}: Unknown command: ${cmd}" ;;
	esac
}

hose::main "$@"
